sinam_core_farmcatalogoproductos:
    resource: "@SinamCoreBundle/Resources/config/routing/farmcatalogoproductos.yml"
    prefix:   /farmcatalogoproductos

sinam_core_ctlmunicipio:
    resource: "@SinamCoreBundle/Resources/config/routing/ctlmunicipio.yml"
    prefix:   /ctlmunicipio

sinam_core_homepage:
    path:     /
    defaults: { _controller: SinamCoreBundle:Default:index }
    methods:  [POST]
    
sinam_busqueda:
    path:     /consulta_medicamento
    defaults: { _controller: SinamCoreBundle:Default:search }
    
ajax_busqueda:
    path:     /buscarajax
    defaults: { _controller: SinamCoreBundle:Default:ajax }
    methods:  [GET|HEAD|POST]
    requirements:
        _method:  POST|GET

ajax_localidad:
    path:     /ajax_localidad
    defaults: { _controller: SinamCoreBundle:PorEstablecimiento:ajax }
    methods:  [GET|HEAD|POST]
    requirements:
        _method:  POST|GET

jsonmedicamentos:
    path:     /jsonmedicamentos
    defaults: { _controller: SinamCoreBundle:Default:jsonmedicamentos }
    methods:  [GET|HEAD|POST]
    requirements:
        _method:  POST|GET

por_establecimiento:
    path:     /consulta_establecimiento
    defaults: { _controller: SinamCoreBundle:PorEstablecimiento:index }

alternativo:
    path:     /alternativo
    defaults: { _controller: SinamCoreBundle:Default:alternativo }

consulta_abastecimiento:
    path:     /consulta_abastecimiento
    defaults: { _controller: SinamCoreBundle:PorAbastecimiento:index }

info_establecimiento:
    path:     /info_establecimiento
    defaults: { _controller: SinamCoreBundle:Info:establecimiento }

info_contacto:
    path:     /info_contacto
    defaults: { _controller: SinamCoreBundle:Info:contacto }

info_ayuda:
    path:     /mostrar
    defaults: { _controller: SinamCoreBundle:Info:mostrar }