services:
#    sinam_core.example:
#        class: Sinam\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
services:
#    sinam.twig.controller_action_extension:
#        class: Sinam\CoreBundle\Twig\Extension\ControllerActionExtension
#        calls:
#            - [setRequest, ["@?request="]]
#        tags:
#s            - { name: twig.extension }
