<?php

namespace Sinam\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Sinam\CoreBundle\Entity\FarmCatalogoproductos;
use Sinam\CoreBundle\Entity\CtlMunicipio;

/**
 * SinamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SinamRepository extends EntityRepository
{
	function findByNombreMedicamento( $nombre ){
		$repository = $this->getDoctrine()->getRepository('SinamCoreBundle:FarmMedicinaexistenciaxarea');
		$query = $repository->createQueryBuilder('e')
			->select('e')
			->addSelect('s.direccion, s.nombre AS nombree')
			->innerJoin('e.idmedicina', 'm')
			->innerJoin('e.idestablecimiento', 's')
			->where("m.nombre ILIKE '%".$nombre."%' AND e.existencia > 0 ")
			->addSelect('m.nombre, m.formafarmaceutica, m.presentacion, e.existencia')
			->getQuery()->getResult();	
    	return $query;
    }
}
