<?php

namespace Proxies\__CG__\Sinam\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CtlInstitucion extends \Sinam\CoreBundle\Entity\CtlInstitucion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\CtlInstitucion' . "\0" . 'id', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\CtlInstitucion' . "\0" . 'nombre', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\CtlInstitucion' . "\0" . 'logo', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\CtlInstitucion' . "\0" . 'rectora', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\CtlInstitucion' . "\0" . 'categoria', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\CtlInstitucion' . "\0" . 'sigla', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\CtlInstitucion' . "\0" . 'estado', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\CtlInstitucion' . "\0" . 'idPais');
        }

        return array('__isInitialized__', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\CtlInstitucion' . "\0" . 'id', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\CtlInstitucion' . "\0" . 'nombre', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\CtlInstitucion' . "\0" . 'logo', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\CtlInstitucion' . "\0" . 'rectora', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\CtlInstitucion' . "\0" . 'categoria', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\CtlInstitucion' . "\0" . 'sigla', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\CtlInstitucion' . "\0" . 'estado', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\CtlInstitucion' . "\0" . 'idPais');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CtlInstitucion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo($logo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo', array($logo));

        return parent::setLogo($logo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', array());

        return parent::getLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setRectora($rectora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRectora', array($rectora));

        return parent::setRectora($rectora);
    }

    /**
     * {@inheritDoc}
     */
    public function getRectora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRectora', array());

        return parent::getRectora();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoria($categoria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoria', array($categoria));

        return parent::setCategoria($categoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoria', array());

        return parent::getCategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setSigla($sigla)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSigla', array($sigla));

        return parent::setSigla($sigla);
    }

    /**
     * {@inheritDoc}
     */
    public function getSigla()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSigla', array());

        return parent::getSigla();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPais(\Sinam\CoreBundle\Entity\CtlPais $idPais = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPais', array($idPais));

        return parent::setIdPais($idPais);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPais', array());

        return parent::getIdPais();
    }

}
