<?php

namespace Proxies\__CG__\Sinam\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FarmLotes extends \Sinam\CoreBundle\Entity\FarmLotes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\FarmLotes' . "\0" . 'id', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\FarmLotes' . "\0" . 'lote', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\FarmLotes' . "\0" . 'preciolote', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\FarmLotes' . "\0" . 'fechavencimiento', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\FarmLotes' . "\0" . 'idestablecimiento', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\FarmLotes' . "\0" . 'idmodalidad', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\FarmLotes' . "\0" . 'idprocedencia', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\FarmLotes' . "\0" . 'idTransIngreso', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\FarmLotes' . "\0" . 'fechaIngreso');
        }

        return array('__isInitialized__', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\FarmLotes' . "\0" . 'id', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\FarmLotes' . "\0" . 'lote', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\FarmLotes' . "\0" . 'preciolote', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\FarmLotes' . "\0" . 'fechavencimiento', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\FarmLotes' . "\0" . 'idestablecimiento', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\FarmLotes' . "\0" . 'idmodalidad', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\FarmLotes' . "\0" . 'idprocedencia', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\FarmLotes' . "\0" . 'idTransIngreso', '' . "\0" . 'Sinam\\CoreBundle\\Entity\\FarmLotes' . "\0" . 'fechaIngreso');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FarmLotes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLote($lote)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLote', array($lote));

        return parent::setLote($lote);
    }

    /**
     * {@inheritDoc}
     */
    public function getLote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLote', array());

        return parent::getLote();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreciolote($preciolote)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreciolote', array($preciolote));

        return parent::setPreciolote($preciolote);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreciolote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreciolote', array());

        return parent::getPreciolote();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechavencimiento($fechavencimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechavencimiento', array($fechavencimiento));

        return parent::setFechavencimiento($fechavencimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechavencimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechavencimiento', array());

        return parent::getFechavencimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdestablecimiento($idestablecimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdestablecimiento', array($idestablecimiento));

        return parent::setIdestablecimiento($idestablecimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdestablecimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdestablecimiento', array());

        return parent::getIdestablecimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdmodalidad($idmodalidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdmodalidad', array($idmodalidad));

        return parent::setIdmodalidad($idmodalidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdmodalidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmodalidad', array());

        return parent::getIdmodalidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdprocedencia($idprocedencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdprocedencia', array($idprocedencia));

        return parent::setIdprocedencia($idprocedencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdprocedencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdprocedencia', array());

        return parent::getIdprocedencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTransIngreso($idTransIngreso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTransIngreso', array($idTransIngreso));

        return parent::setIdTransIngreso($idTransIngreso);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTransIngreso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTransIngreso', array());

        return parent::getIdTransIngreso();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaIngreso($fechaIngreso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaIngreso', array($fechaIngreso));

        return parent::setFechaIngreso($fechaIngreso);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaIngreso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaIngreso', array());

        return parent::getFechaIngreso();
    }

}
