services:
    ewz_recaptcha.form.type:
        class: EWZ\Bundle\RecaptchaBundle\Form\Type\EWZRecaptchaType
        arguments:
            - '%ewz_recaptcha.public_key%'
            - '%ewz_recaptcha.enabled%'
            - '%ewz_recaptcha.ajax%'
            - '%ewz_recaptcha.locale_key%'
        tags:
            - { name: form.type }

    ewz_recaptcha.validator.true:
            class: EWZ\Bundle\RecaptchaBundle\Validator\Constraints\IsTrueValidator
            arguments:
                - '%ewz_recaptcha.enabled%'
                - '%ewz_recaptcha.private_key%'
                - '@request_stack'
                - '%ewz_recaptcha.http_proxy%'
            tags:
                - { name: validator.constraint_validator, alias: 'ewz_recaptcha.true' }