Sinam\CoreBundle\Entity\CtlMunicipio:
    type: entity
    table: ctl_municipio
    indexes:
        IDX_914172ED6325E299:
            columns:
                - id_departamento
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Llave primaria'
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombre:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: 'Nombre del municipio'
        codigoCnr:
            type: string
            nullable: true
            length: 5
            fixed: false
            comment: 'Codigo asignado por la Digestyc para un municipio en especifico'
            column: codigo_cnr
        abreviatura:
            type: string
            nullable: true
            length: 5
            fixed: false
            comment: 'Abreviatura asignada al municipio'
    manyToOne:
        idDepartamento:
            targetEntity: CtlDepartamento
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_departamento:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        idSinab:
            targetEntity: SabCatMunicipios
            cascade: {  }
            mappedBy: null
            inversedBy: idSiap
            joinTable:
                name: ctl_alias_municipio
                joinColumns:
                    -
                        name: id_siap
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: id_sinab
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
