Sinam\CoreBundle\Entity\CtlMunicipio:
    type: entity
    table: ctl_municipio
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Llave primaria'
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombre:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: 'Nombre del municipio'
        codigoCnr:
            type: string
            nullable: true
            length: 5
            fixed: false
            comment: 'Codigo asignado por la Digestyc para un municipio en especifico'
            column: codigo_cnr
        abreviatura:
            type: string
            nullable: true
            length: 5
            fixed: false
            comment: 'Abreviatura asignada al municipio'
        idDepartamento:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Representa la llave foranea que proviene de ctl_departamento'
            column: id_departamento
    lifecycleCallbacks: {  }
