Sinam\CoreBundle\Entity\MntAreafarmaciaxestablecimiento:
    type: entity
    table: mnt_areafarmaciaxestablecimiento
    indexes:
        IDX_2B5F8AA845BCCC8:
            columns:
                - idarea
        IDX_2B5F8AA875BB31F7:
            columns:
                - idestablecimiento
    id:
        idrelacion:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Llave primaria'
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        habilitado:
            type: string
            nullable: false
            length: 1
            fixed: true
            comment: 'Estado de Area de farmacia'
            default: S
        idmodalidad:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Identificador del tipo de modalidad en las que se desenvuelve el establecimiento'
        cargaSinab:
            type: boolean
            nullable: false
            comment: 'define el area de la farmacia por defecto donde se cargara el vale proveniente de SINAB.'
            default: false
            column: carga_sinab
        dispensarSeguimiento:
            type: boolean
            nullable: true
            default: false
            column: dispensar_seguimiento
    manyToOne:
        idarea:
            targetEntity: MntAreafarmacia
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idarea:
                    referencedColumnName: id
            orphanRemoval: false
        idestablecimiento:
            targetEntity: SabCatEstablecimientos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idestablecimiento:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
