Sinam\CoreBundle\Entity\SabAlmExistenciahistorica:
    type: entity
    table: sab_alm_existenciahistorica
    indexes:
        IDX_E4D147E1B2F7B20:
            columns:
                - id_almacen
        IDX_E4D147E1F760EA80:
            columns:
                - id_producto
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        fecha:
            type: datetime
            nullable: false
        cantidaddisponible:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
        cantidadnodisponible:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
        cantidadreservada:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
        cantidadtemporal:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
        cantidadvencida:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
    manyToOne:
        idAlmacen:
            targetEntity: SabCatAlmacenes
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_almacen:
                    referencedColumnName: id
            orphanRemoval: false
        idProducto:
            targetEntity: SabCatCatalogoproductos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_producto:
                    referencedColumnName: idpro
            orphanRemoval: false
    lifecycleCallbacks: {  }
