Sinam\CoreBundle\Entity\SabCatInstituciones:
    type: entity
    table: sab_cat_instituciones
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombre:
            type: string
            nullable: false
            length: 50
            fixed: false
        porcentajereserva:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
        estasincronizada:
            type: smallint
            nullable: false
            unsigned: false
            default: '0'
    lifecycleCallbacks: {  }
