Sinam\CoreBundle\Entity\SabCatDepartamentos:
    type: entity
    table: sab_cat_departamentos
    uniqueConstraints:
        sab_cat_departamentos_codigodepartamento_key:
            columns:
                - codigodepartamento
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        codigodepartamento:
            type: string
            nullable: false
            length: 2
            fixed: true
        nombre:
            type: string
            nullable: false
            length: 20
            fixed: false
        estasincronizada:
            type: smallint
            nullable: false
            unsigned: false
            default: '0'
    lifecycleCallbacks: {  }
