Sinam\CoreBundle\Entity\SabCatAlmacenes:
    type: entity
    table: sab_cat_almacenes
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombre:
            type: string
            nullable: false
            length: 70
            fixed: false
        direccion:
            type: string
            nullable: true
            length: 200
            fixed: false
        telefono:
            type: string
            nullable: true
            length: 8
            fixed: false
            default: '0'
        esfarmacia:
            type: smallint
            nullable: false
            unsigned: false
            default: '0'
        estasincronizada:
            type: smallint
            nullable: false
            unsigned: false
            default: '0'
        estadoalmacen:
            type: smallint
            nullable: true
            unsigned: false
    lifecycleCallbacks: {  }
