Sinam\CoreBundle\Entity\SabCatAlternativasproducto:
    type: entity
    table: sab_cat_alternativasproducto
    indexes:
        IDX_3B4B8BFEF760EA80:
            columns:
                - id_producto
    id: {  }
    fields:
        multiplicador:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
            default: '(1)::numeric'
        divisor:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
            default: '(1)::numeric'
        estasincronizada:
            type: smallint
            nullable: false
            unsigned: false
            default: '0'
    manyToOne:
        idProducto:
            targetEntity: SabCatCatalogoproductos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_producto:
                    referencedColumnName: idpro
            orphanRemoval: false
    oneToOne:
        id:
            targetEntity: SabCatCatalogoproductos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id:
                    referencedColumnName: idpro
            orphanRemoval: false
    lifecycleCallbacks: {  }
