ctlmunicipio_index:
    path:     /
    defaults: { _controller: "SinamCoreBundle:CtlMunicipio:index" }
    methods:  GET

ctlmunicipio_show:
    path:     /{id}/show
    defaults: { _controller: "SinamCoreBundle:CtlMunicipio:show" }
    methods:  GET

ctlmunicipio_new:
    path:     /new
    defaults: { _controller: "SinamCoreBundle:CtlMunicipio:new" }
    methods:  [GET, POST]

ctlmunicipio_edit:
    path:     /{id}/edit
    defaults: { _controller: "SinamCoreBundle:CtlMunicipio:edit" }
    methods:  [GET, POST]

ctlmunicipio_delete:
    path:     /{id}/delete
    defaults: { _controller: "SinamCoreBundle:CtlMunicipio:delete" }
    methods:  DELETE
