farmcatalogoproductos_index:
    path:     /
    defaults: { _controller: "SinamCoreBundle:FarmCatalogoproductos:index" }
    methods:  GET

farmcatalogoproductos_show:
    path:     /{id}/show
    defaults: { _controller: "SinamCoreBundle:FarmCatalogoproductos:show" }
    methods:  GET

farmcatalogoproductos_new:
    path:     /new
    defaults: { _controller: "SinamCoreBundle:FarmCatalogoproductos:new" }
    methods:  [GET, POST]

farmcatalogoproductos_edit:
    path:     /{id}/edit
    defaults: { _controller: "SinamCoreBundle:FarmCatalogoproductos:edit" }
    methods:  [GET, POST]

farmcatalogoproductos_delete:
    path:     /{id}/delete
    defaults: { _controller: "SinamCoreBundle:FarmCatalogoproductos:delete" }
    methods:  DELETE
